### ISSUE TITLE
Exporting to version-3 doesn't work on 2021E Rōblox.

### ISSUE THREAD

**Issue by Windows81** [PrintedScript/RBXMesh#2]
I'm running a Rōblox server on [a custom procurement system](https://github.com/Windows81/Roblox-Freedom-Distribution) using binaries from 2021-01-26.  To load each asset, I retrieve it directly from Rōblox's servers.  If that asset is a mesh, I use your library and convert it to a version-**2** mesh.

Version-2 meshes work well, but version-3 meshes don't parse correctly.  Here's an example error line I get on the client:

```
1716541948.19264,c0cc,6 [FLog::Error] Error: MeshContentProvider failed to process https://127.0.0.1:2006/v1/asset?id=47963332 because Error reading mesh data: empty mesh
```

I still need to expand on this.

**Comment by PrintedScript** [comment]
Hi, this should now be fixed. Issue was caused when reading Mesh V2 and V1 which cannot store any LOD info, so when exported to V3 which does require LOD info, the amount of LODs written to the file is 0 which causes ROBLOX to raise a "empty mesh" exception as it expects at least 2 LODs

However I do recommend to only export to mesh V3 if you are reading meshes V3 and above as exporting V2 and V1 to V3 has no real benefit as they are not able to benefit from V3
